### ISSUE TITLE
undefined method `current_jwt_auth='

### ISSUE THREAD

**Issue by pawelniewie** [MeisterLabs/atlassian-jwt-authentication#4]
Hi Laura,
after your recent changes the gem was failing with:

```
undefined method `current_jwt_auth='
```

Backtrace was:

```
/usr/local/opt/rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/atlassian-jwt-authentication-964291a55fe3/lib/atlassian-jwt-authentication/filters.rb:31:in `on_add_on_installed'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.0.rc1) lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
actionpack (5.0.0.rc1) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
```

Here's how I fixed it:

``` diff
diff --git a/lib/atlassian-jwt-authentication/filters.rb b/lib/atlassian-jwt-authentication/filters.rb
index fad02a6..3a0736b 100644
--- a/lib/atlassian-jwt-authentication/filters.rb
+++ b/lib/atlassian-jwt-authentication/filters.rb
@@ -1,7 +1,10 @@
 require 'jwt'
+require 'atlassian-jwt-authentication/helper'

 module AtlassianJwtAuthentication
   module Filters
+       include AtlassianJwtAuthentication::Helper
+
     protected

     def on_add_on_installed
```

**Comment by bulinutza** [comment]
That's probably because you are including AtlassianJwtAuthentication::Filters. I changed it so that you can include the whole module without worrying about individual modules, so if you use include AtlassianJwtAuthentication it should work. Please let me know :-)

**Comment by bulinutza** [comment]
Ah, I see I forgot to update the documentation, oops!

**Comment by bulinutza** [comment]
Ok, I updated it now: https://github.com/MeisterLabs/atlassian-jwt-authentication#2-controller-filters

**Comment by pawelniewie** [comment]
Yeah, that was the case, I was still including ::Filters, thanks!
